version: '3.8'

services:
  vector:
    image: timberio/vector:0.34.0-distroless-libc
    container_name: vector
    ports:
      - "8686:8686"  # Vector API and web UI
      - "9598:9598"  # Vector metrics
      - "514:514"    # Syslog TCP
      - "514:514/udp" # Syslog UDP
    volumes:
      - ./vector/vector.toml:/etc/vector/vector.toml:ro
      - ./vector/data:/var/lib/vector
    depends_on:
      - loki
    networks:
      - logging
    restart: unless-stopped

  loki:
    image: grafana/loki:2.9.2
    container_name: loki
    ports:
      - "3100:3100"
    volumes:
      - ./loki/loki-config.yml:/etc/loki/local-config.yaml:ro
      - loki-data:/loki
    command: -config.file=/etc/loki/local-config.yaml
    networks:
      - logging
    restart: unless-stopped

  grafana:
    image: grafana/grafana:10.2.2
    container_name: grafana
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_USERS_ALLOW_SIGN_UP=false
    volumes:
      - grafana-data:/var/lib/grafana
      - ./grafana/provisioning:/etc/grafana/provisioning:ro
      - ./grafana/dashboards:/var/lib/grafana/dashboards:ro
    depends_on:
      - loki
    networks:
      - logging
    restart: unless-stopped

volumes:
  loki-data:
    driver: local
  grafana-data:
    driver: local

networks:
  logging:
    driver: bridge