[api]
enabled = true
address = "0.0.0.0:8686"

[sources.demo_logs]
type = "demo_logs"
format = "syslog"
count = 100

[sources.syslog]
type = "syslog"
address = "0.0.0.0:514"
mode = "tcp"

[sources.file_logs]
type = "file"
include = ["/var/log/*.log"]
ignore_older_secs = 600

[transforms.parse_logs]
type = "remap"
inputs = ["demo_logs", "syslog", "file_logs"]
source = """
  .timestamp = now()
  .service = "vector-demo"
  if exists(.message) {
    .message = string!(.message)
  }
"""

[sinks.loki]
type = "loki"
inputs = ["parse_logs"]
endpoint = "http://loki:3100"
encoding.codec = "json"
labels.service = "{{ service }}"
labels.source = "vector"

[sinks.console]
type = "console"
inputs = ["parse_logs"]
encoding.codec = "json"
